services:
    rent_app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: rent_app
        restart: unless-stopped
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - postgres
    postgres:
        image: postgres
        container_name: postgres
        restart: always
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app-network
        expose:
            - 5432

    rent_pgadmin:
        image: dpage/pgadmin4
        container_name: rent_pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - "8081:8008"
        networks:
            - app-network

    rent_nginx:
        container_name: rent_nginx
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - rent_app
        networks:
            - app-network

    rent_node:
        container_name: rent_node
        image: node:20
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - app-network
        command: bash -c "npm install && npm run build"

volumes:
    postgres_data:

networks:
    app-network:
        driver: bridge
